# IDEA auto formatter is causing trouble
# @formatter:off
name: Node.js Build (Dev)

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Check out
        uses: actions/checkout@v1

      - name: Install deps
        run: npm install

      - name: Schema Validation
        run: npm run validate

      - name: Build
        run: |
          npm run build:dev
          ls -alh dist/
