# IDEA auto formatter is causing trouble
# @formatter:off
name: Node.js Build (Production)

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Check out
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm ci
          npm run build
          ls -alh dist/
